
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
app_name = "#{app_identifier}"

MY_DEV_PROFILE = "match Development com.unity.cloud.reference-projec"
RELEASE_PROFILE = "match Development com.unity.cloud.reference-projec"
RELEASE_TYPE = "development"
GYM_RELEASE_TYPE = "development"
MY_TEAM = "BVPN9UFA9B"
XCODE_PROJ = "./Builds/iOS/Unity-iPhone.xcodeproj"

# Unity
platform :ios do
    default_platform(:ios)
    
    app_store_connect_api_key(
        key_id: ENV["APPSTORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APPSTORE_CONNECT_API_ISSUER_ID"],
        key_content: ENV["APPSTORE_CONNECT_API_KEY"],
    )

    lane :test do        
        buildNum = latest_testflight_build_number(            
            live: false,
            app_identifier: app_name,            
        )        
        message = "Test Message " + "#{buildNum}"
        UI.message(message)
    end    
    
    desc "Test Match"
    lane :match_test do
        match(
            force_for_new_devices: true,
            type: "appstore",
            app_identifier: "#{app_identifier}",
            git_branch: "#{app_identifier}",
            readonly: true,
            generate_apple_certs: false,
            git_url: "git@github.com:Unity-Technologies/fastlane_certificates.git",            
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            verbose: true,
            output_path: "./certs",
            platform: "ios"
        )
    end

    desc "Build a development APK"
    lane :development_build do
        run_build()        
    end

    desc "Builds a distribution APK"
    lane :distribution_build do        
        run_build(
            :RELEASE_TYPE => "appstore",
            :GYM_RELEASE_TYPE => "app-store"
            )        
    end

    desc "Makes the build!"
    lane :run_build do |options|
        begin
        #if any of these options aren't set, assume we're running a local build
        if !options[:RELEASE_TYPE] || !options[:GYM_RELEASE_TYPE]
            options[:RELEASE_TYPE] = "development"
            options[:GYM_RELEASE_TYPE] = "development"
        end

        match(
            force_for_new_devices: true,
            type: "#{options[:RELEASE_TYPE]}",
            app_identifier: "#{app_identifier}",
            git_branch: "#{app_identifier}",
            readonly: true,
            generate_apple_certs: false,
            git_url: "git@github.com:Unity-Technologies/fastlane_certificates.git",            
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            verbose: true,
        )
        
        update_code_signing_settings(        
            team_id: "#{MY_TEAM}",
            use_automatic_signing: false,
            profile_name: "#{RELEASE_PROFILE}",
            path: "#{XCODE_PROJ}",
            code_sign_identity: "iPhone Distribution: Unity Technologies ApS (BVPN9UFA9B)",
            targets: "Unity-iPhone",
        )        
        update_code_signing_settings(
            # team_id: "#{MY_TEAM}",          
            use_automatic_signing: true,
            profile_name: "",              
            path: "#{XCODE_PROJ}",                        
            targets: "UnityFramework",
        )

        settings_to_override = {
            :BUNDLE_IDENTIFIER => "#{app_identifier}",
            :DEVELOPMENT_TEAM => MY_TEAM,
           # :PROVISIONING_PROFILE_SPECIFIER => RELEASE_PROFILE,             
        }
        gym(            
            include_symbols: true,            
            scheme: "Unity-iPhone",
            skip_profile_detection: true,
            silent: false,
            configuration: "Release",
            project: "#{XCODE_PROJ}",
            clean: true,
            xcargs: settings_to_override,
            output_directory: "Builds/",
            export_method: "#{options[:GYM_RELEASE_TYPE]}",            
            export_options: {                
                method: "#{options[:GYM_RELEASE_TYPE]}",
                # provisionProfiles: {
                 #   "#{app_identifier}" => RELEASE_PROFILE,
                # },
            },
        )        

        rescue => ex
            UI.message(ex)
        end
    end    

    desc "publish build to testflight"
    lane :publish_to_testflight do
        pilot(
            app_identifier: "#{app_identifier}",
            ipa: "./Builds/Unity Cloud Reference Project.ipa"
        )
    end

    desc "Update Build Number"
    lane :increment do
        ver = get_version_number(
            xcodeproj: "#{XCODE_PROJ}",
            target: "Unity-iPhone",
        )
        x = app_store_build_number(
            initial_build_number: 0,
            live: false,
            app_identifier: "com.unity.cloud.reference-project",
            version: ver,
        )
        increment_build_number(
            xcodeproj: "#{XCODE_PROJ}",
            build_number: x + 1,
        )
        buildNum = get_build_number(
            xcodeproj: "#{XCODE_PROJ}",
        )
        message = "Finished Unity Build, Beginning XCode Build"
        UI.message(message)    
    end
end

platform :mac do
    default_platform(:mac)
    lane :get_certs do
        match(
            force_for_new_devices: true,
            type: "development",
            app_identifier: "#{app_identifier}",
            git_branch: "#{app_identifier}",
            readonly: true,
            generate_apple_certs: false,
            git_url: "git@github.com:Unity-Technologies/fastlane_certificates.git",            
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            verbose: true,
            output_path: "./certs",
            skip_provisioning_profiles: true,
        )      
    end
end
